[project]
name = "twstockmcpserver"
version = "0.1.0"
description = "A MCPServer for partial APIs of the Taiwan Stock Exchange OpenAPI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.7.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
    "requests>=2.32.4",
]
